version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: piece-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - piece-nw

  redis:
    image: redis/redis-stack:latest
    container_name: piece-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - piece-nw

volumes:
  mysql-data:
  redis-data:

networks:
  piece-nw:
