FROM eclipse-temurin:17-jdk

ARG JAR_FILE=api/build/libs/*.jar

ENV TZ=Asia/Seoul

RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime \
    && echo "Asia/Seoul" > /etc/timezone \

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]