name: CI/CD Admin Application - Prod

on:
  push:
    branches: [ "main" ]
    paths:
      - "admin/**"
      - "core/domain/**"
      - "core/format/**"
      - "core/exception/**"
      - "core/auth/**"
      - "core/notification/**"
      - "infra/discord/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: make ADMIN application-secret.yml
        run: |
          cd ./admin/src/main/resources
          touch ./application-secret.yml 
          echo "${{ secrets.ADMIN_PROD_YML }}" > ./application-secret.yml
        shell: bash

      - name: Build ADMIN with Gradle
        run: |
          chmod u+x ./gradlew
          ./gradlew :admin:build -x test

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Docker build & push ADMIN to prod
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-admin -t ${{ secrets.DOCKER_USERNAME }}/piece-admin-prod:${{ env.IMAGE_TAG }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/piece-admin-prod:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/piece-admin-prod:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/piece-admin-prod:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/piece-admin-prod:latest

      - name: Deploy ADMIN to prod
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST_ADMIN_PROD }}
          username: ${{ secrets.HOST_ADMIN_PROD_USERNAME }}
          port: 22
          key: ${{ secrets.HOST_ADMIN_PROD_PRIVATE_KEY }}
          script: |
            sudo docker stop piece-admin-prod || true
            sudo docker rm piece-admin-prod || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/piece-admin-prod:${{ env.IMAGE_TAG }}
            sudo docker run -d --name piece-admin-prod -p 8080:8080 --network piece-nw ${{ secrets.DOCKER_USERNAME }}/piece-admin-prod:${{ env.IMAGE_TAG }}
            sudo docker image prune -f